### ISSUE TITLE
setting key "vm.overcommit_memory": Read-only file system

### ISSUE THREAD

**Issue by CybotTM** [openfirmware/docker-redis#1]
```
sysctl vm.overcommit_memory=1
sysctl: setting key "vm.overcommit_memory": Read-only file system
```

see https://github.com/docker-library/redis/issues/19

**Comment by openfirmware** [comment]
Thanks for the heads up, I am taking a look at the cause.

**Comment by openfirmware** [comment]
It appears that `/proc` is read-only ([docker#5703](https://github.com/docker/docker/issues/5703)), and `sysctl` cannot edit the vm overcommit memory setting unless docker runs the container with the `--privileged` setting ([source](https://docs.docker.com/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration)). This does change the value on the docker host as well.

This leaves three options.
1. Enable `sysctl vm.overcommit_memory=1` on the docker host and it will apply to all running containers, including docker-redis.
2. Run docker-redis with `--privileged`, thus enabling `vm.overcommit_memory` for the docker host and all other containers. I do not recommend this as it is not obvious that the container made a change to your docker host.
3. Run docker-redis as-is and let Redis run without `vm.overcommit_memory`.

I will update the README to note this limitation.

**Comment by CVirus** [comment]
Enabling sysctl vm.overcommit_memory=1 on the docker host will NOT be inherited by the running containers :-(

EDIT1: Yes it will inherit.
EDIT2: It won't inherit on some OS configurations/machines.. still investigating.
EDIT3: Final findings .. overcommit_memory is inherited in all cases (my bad) .. somaxconn is inherited **only** when the container runs in host networking mode.

**Comment by Mehonoshin** [comment]
Hey, folks. Has anyone solved this issue?

**Comment by 0xO0O0** [comment]
anyone at all?

**Comment by openfirmware** [comment]
I checked with Docker 17.03.1-ce today and option #1 I mentioned above seems to work on Ubuntu 14.04.5 LTS host:

```shell
host# sysctl vm.overcommit_memory
vm.overcommit_memory = 0
host# docker run -it --rm openfirmware/redis sysctl vm.overcommit_memory
vm.overcommit_memory = 0
host# sysctl vm.overcommit_memory=1
vm.overcommit_memory = 1
host# sysctl vm.overcommit_memory
vm.overcommit_memory = 0
host# docker run -it --rm openfirmware/redis sysctl vm.overcommit_memory
vm.overcommit_memory = 1
```

Option #2 doesn't work for me though. Let me know if that doesn't work for you.
